// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: loadConf.proto

#ifndef PROTOBUF_loadConf_2eproto__INCLUDED
#define PROTOBUF_loadConf_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003002 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/descriptor.pb.h>
// @@protoc_insertion_point(includes)
namespace google {
namespace protobuf {
class DescriptorProto;
class DescriptorProtoDefaultTypeInternal;
extern DescriptorProtoDefaultTypeInternal _DescriptorProto_default_instance_;
class DescriptorProto_ExtensionRange;
class DescriptorProto_ExtensionRangeDefaultTypeInternal;
extern DescriptorProto_ExtensionRangeDefaultTypeInternal _DescriptorProto_ExtensionRange_default_instance_;
class DescriptorProto_ReservedRange;
class DescriptorProto_ReservedRangeDefaultTypeInternal;
extern DescriptorProto_ReservedRangeDefaultTypeInternal _DescriptorProto_ReservedRange_default_instance_;
class EnumDescriptorProto;
class EnumDescriptorProtoDefaultTypeInternal;
extern EnumDescriptorProtoDefaultTypeInternal _EnumDescriptorProto_default_instance_;
class EnumOptions;
class EnumOptionsDefaultTypeInternal;
extern EnumOptionsDefaultTypeInternal _EnumOptions_default_instance_;
class EnumValueDescriptorProto;
class EnumValueDescriptorProtoDefaultTypeInternal;
extern EnumValueDescriptorProtoDefaultTypeInternal _EnumValueDescriptorProto_default_instance_;
class EnumValueOptions;
class EnumValueOptionsDefaultTypeInternal;
extern EnumValueOptionsDefaultTypeInternal _EnumValueOptions_default_instance_;
class FieldDescriptorProto;
class FieldDescriptorProtoDefaultTypeInternal;
extern FieldDescriptorProtoDefaultTypeInternal _FieldDescriptorProto_default_instance_;
class FieldOptions;
class FieldOptionsDefaultTypeInternal;
extern FieldOptionsDefaultTypeInternal _FieldOptions_default_instance_;
class FileDescriptorProto;
class FileDescriptorProtoDefaultTypeInternal;
extern FileDescriptorProtoDefaultTypeInternal _FileDescriptorProto_default_instance_;
class FileDescriptorSet;
class FileDescriptorSetDefaultTypeInternal;
extern FileDescriptorSetDefaultTypeInternal _FileDescriptorSet_default_instance_;
class FileOptions;
class FileOptionsDefaultTypeInternal;
extern FileOptionsDefaultTypeInternal _FileOptions_default_instance_;
class GeneratedCodeInfo;
class GeneratedCodeInfoDefaultTypeInternal;
extern GeneratedCodeInfoDefaultTypeInternal _GeneratedCodeInfo_default_instance_;
class GeneratedCodeInfo_Annotation;
class GeneratedCodeInfo_AnnotationDefaultTypeInternal;
extern GeneratedCodeInfo_AnnotationDefaultTypeInternal _GeneratedCodeInfo_Annotation_default_instance_;
class MessageOptions;
class MessageOptionsDefaultTypeInternal;
extern MessageOptionsDefaultTypeInternal _MessageOptions_default_instance_;
class MethodDescriptorProto;
class MethodDescriptorProtoDefaultTypeInternal;
extern MethodDescriptorProtoDefaultTypeInternal _MethodDescriptorProto_default_instance_;
class MethodOptions;
class MethodOptionsDefaultTypeInternal;
extern MethodOptionsDefaultTypeInternal _MethodOptions_default_instance_;
class OneofDescriptorProto;
class OneofDescriptorProtoDefaultTypeInternal;
extern OneofDescriptorProtoDefaultTypeInternal _OneofDescriptorProto_default_instance_;
class OneofOptions;
class OneofOptionsDefaultTypeInternal;
extern OneofOptionsDefaultTypeInternal _OneofOptions_default_instance_;
class ServiceDescriptorProto;
class ServiceDescriptorProtoDefaultTypeInternal;
extern ServiceDescriptorProtoDefaultTypeInternal _ServiceDescriptorProto_default_instance_;
class ServiceOptions;
class ServiceOptionsDefaultTypeInternal;
extern ServiceOptionsDefaultTypeInternal _ServiceOptions_default_instance_;
class SourceCodeInfo;
class SourceCodeInfoDefaultTypeInternal;
extern SourceCodeInfoDefaultTypeInternal _SourceCodeInfo_default_instance_;
class SourceCodeInfo_Location;
class SourceCodeInfo_LocationDefaultTypeInternal;
extern SourceCodeInfo_LocationDefaultTypeInternal _SourceCodeInfo_Location_default_instance_;
class UninterpretedOption;
class UninterpretedOptionDefaultTypeInternal;
extern UninterpretedOptionDefaultTypeInternal _UninterpretedOption_default_instance_;
class UninterpretedOption_NamePart;
class UninterpretedOption_NamePartDefaultTypeInternal;
extern UninterpretedOption_NamePartDefaultTypeInternal _UninterpretedOption_NamePart_default_instance_;
}  // namespace protobuf
}  // namespace google
namespace load {
class LoadSet;
class LoadSetDefaultTypeInternal;
extern LoadSetDefaultTypeInternal _LoadSet_default_instance_;
class SchoolAtr;
class SchoolAtrDefaultTypeInternal;
extern SchoolAtrDefaultTypeInternal _SchoolAtr_default_instance_;
class SchoolConf;
class SchoolConfDefaultTypeInternal;
extern SchoolConfDefaultTypeInternal _SchoolConf_default_instance_;
class SchoolSudent;
class SchoolSudentDefaultTypeInternal;
extern SchoolSudentDefaultTypeInternal _SchoolSudent_default_instance_;
}  // namespace load

namespace load {

namespace protobuf_loadConf_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_loadConf_2eproto

enum XmlInfo {
  Xml_none = 0,
  Xml_school = 1,
  XmlInfo_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  XmlInfo_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool XmlInfo_IsValid(int value);
const XmlInfo XmlInfo_MIN = Xml_none;
const XmlInfo XmlInfo_MAX = Xml_school;
const int XmlInfo_ARRAYSIZE = XmlInfo_MAX + 1;

const ::google::protobuf::EnumDescriptor* XmlInfo_descriptor();
inline const ::std::string& XmlInfo_Name(XmlInfo value) {
  return ::google::protobuf::internal::NameOfEnum(
    XmlInfo_descriptor(), value);
}
inline bool XmlInfo_Parse(
    const ::std::string& name, XmlInfo* value) {
  return ::google::protobuf::internal::ParseNamedEnum<XmlInfo>(
    XmlInfo_descriptor(), name, value);
}
// ===================================================================

class LoadSet : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:load.LoadSet) */ {
 public:
  LoadSet();
  virtual ~LoadSet();

  LoadSet(const LoadSet& from);

  inline LoadSet& operator=(const LoadSet& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LoadSet& default_instance();

  static inline const LoadSet* internal_default_instance() {
    return reinterpret_cast<const LoadSet*>(
               &_LoadSet_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(LoadSet* other);

  // implements Message ----------------------------------------------

  inline LoadSet* New() const PROTOBUF_FINAL { return New(NULL); }

  LoadSet* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const LoadSet& from);
  void MergeFrom(const LoadSet& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(LoadSet* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string file = 1;
  void clear_file();
  static const int kFileFieldNumber = 1;
  const ::std::string& file() const;
  void set_file(const ::std::string& value);
  #if LANG_CXX11
  void set_file(::std::string&& value);
  #endif
  void set_file(const char* value);
  void set_file(const char* value, size_t size);
  ::std::string* mutable_file();
  ::std::string* release_file();
  void set_allocated_file(::std::string* file);

  // string msg = 2;
  void clear_msg();
  static const int kMsgFieldNumber = 2;
  const ::std::string& msg() const;
  void set_msg(const ::std::string& value);
  #if LANG_CXX11
  void set_msg(::std::string&& value);
  #endif
  void set_msg(const char* value);
  void set_msg(const char* value, size_t size);
  ::std::string* mutable_msg();
  ::std::string* release_msg();
  void set_allocated_msg(::std::string* msg);

  // @@protoc_insertion_point(class_scope:load.LoadSet)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr file_;
  ::google::protobuf::internal::ArenaStringPtr msg_;
  mutable int _cached_size_;
  friend struct protobuf_loadConf_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SchoolConf : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:load.SchoolConf) */ {
 public:
  SchoolConf();
  virtual ~SchoolConf();

  SchoolConf(const SchoolConf& from);

  inline SchoolConf& operator=(const SchoolConf& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SchoolConf& default_instance();

  static inline const SchoolConf* internal_default_instance() {
    return reinterpret_cast<const SchoolConf*>(
               &_SchoolConf_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(SchoolConf* other);

  // implements Message ----------------------------------------------

  inline SchoolConf* New() const PROTOBUF_FINAL { return New(NULL); }

  SchoolConf* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SchoolConf& from);
  void MergeFrom(const SchoolConf& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SchoolConf* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .load.SchoolSudent student = 2;
  int student_size() const;
  void clear_student();
  static const int kStudentFieldNumber = 2;
  const ::load::SchoolSudent& student(int index) const;
  ::load::SchoolSudent* mutable_student(int index);
  ::load::SchoolSudent* add_student();
  ::google::protobuf::RepeatedPtrField< ::load::SchoolSudent >*
      mutable_student();
  const ::google::protobuf::RepeatedPtrField< ::load::SchoolSudent >&
      student() const;

  // .load.SchoolAtr attr = 1;
  bool has_attr() const;
  void clear_attr();
  static const int kAttrFieldNumber = 1;
  const ::load::SchoolAtr& attr() const;
  ::load::SchoolAtr* mutable_attr();
  ::load::SchoolAtr* release_attr();
  void set_allocated_attr(::load::SchoolAtr* attr);

  // @@protoc_insertion_point(class_scope:load.SchoolConf)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::load::SchoolSudent > student_;
  ::load::SchoolAtr* attr_;
  mutable int _cached_size_;
  friend struct protobuf_loadConf_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SchoolAtr : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:load.SchoolAtr) */ {
 public:
  SchoolAtr();
  virtual ~SchoolAtr();

  SchoolAtr(const SchoolAtr& from);

  inline SchoolAtr& operator=(const SchoolAtr& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SchoolAtr& default_instance();

  static inline const SchoolAtr* internal_default_instance() {
    return reinterpret_cast<const SchoolAtr*>(
               &_SchoolAtr_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(SchoolAtr* other);

  // implements Message ----------------------------------------------

  inline SchoolAtr* New() const PROTOBUF_FINAL { return New(NULL); }

  SchoolAtr* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SchoolAtr& from);
  void MergeFrom(const SchoolAtr& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SchoolAtr* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string name = 1;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // int32 student_num = 2;
  void clear_student_num();
  static const int kStudentNumFieldNumber = 2;
  ::google::protobuf::int32 student_num() const;
  void set_student_num(::google::protobuf::int32 value);

  // float grade = 3;
  void clear_grade();
  static const int kGradeFieldNumber = 3;
  float grade() const;
  void set_grade(float value);

  // @@protoc_insertion_point(class_scope:load.SchoolAtr)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::int32 student_num_;
  float grade_;
  mutable int _cached_size_;
  friend struct protobuf_loadConf_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SchoolSudent : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:load.SchoolSudent) */ {
 public:
  SchoolSudent();
  virtual ~SchoolSudent();

  SchoolSudent(const SchoolSudent& from);

  inline SchoolSudent& operator=(const SchoolSudent& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SchoolSudent& default_instance();

  static inline const SchoolSudent* internal_default_instance() {
    return reinterpret_cast<const SchoolSudent*>(
               &_SchoolSudent_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(SchoolSudent* other);

  // implements Message ----------------------------------------------

  inline SchoolSudent* New() const PROTOBUF_FINAL { return New(NULL); }

  SchoolSudent* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SchoolSudent& from);
  void MergeFrom(const SchoolSudent& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SchoolSudent* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 scores = 3;
  int scores_size() const;
  void clear_scores();
  static const int kScoresFieldNumber = 3;
  ::google::protobuf::int32 scores(int index) const;
  void set_scores(int index, ::google::protobuf::int32 value);
  void add_scores(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      scores() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_scores();

  // string name = 2;
  void clear_name();
  static const int kNameFieldNumber = 2;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // int32 id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:load.SchoolSudent)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > scores_;
  mutable int _scores_cached_byte_size_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::int32 id_;
  mutable int _cached_size_;
  friend struct protobuf_loadConf_2eproto::TableStruct;
};
// ===================================================================

static const int kLoadsetFieldNumber = 1000;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::EnumValueOptions,
    ::google::protobuf::internal::MessageTypeTraits< ::load::LoadSet >, 11, false >
  loadset;

// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// LoadSet

// string file = 1;
inline void LoadSet::clear_file() {
  file_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& LoadSet::file() const {
  // @@protoc_insertion_point(field_get:load.LoadSet.file)
  return file_.GetNoArena();
}
inline void LoadSet::set_file(const ::std::string& value) {
  
  file_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:load.LoadSet.file)
}
#if LANG_CXX11
inline void LoadSet::set_file(::std::string&& value) {
  
  file_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:load.LoadSet.file)
}
#endif
inline void LoadSet::set_file(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  file_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:load.LoadSet.file)
}
inline void LoadSet::set_file(const char* value, size_t size) {
  
  file_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:load.LoadSet.file)
}
inline ::std::string* LoadSet::mutable_file() {
  
  // @@protoc_insertion_point(field_mutable:load.LoadSet.file)
  return file_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LoadSet::release_file() {
  // @@protoc_insertion_point(field_release:load.LoadSet.file)
  
  return file_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LoadSet::set_allocated_file(::std::string* file) {
  if (file != NULL) {
    
  } else {
    
  }
  file_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), file);
  // @@protoc_insertion_point(field_set_allocated:load.LoadSet.file)
}

// string msg = 2;
inline void LoadSet::clear_msg() {
  msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& LoadSet::msg() const {
  // @@protoc_insertion_point(field_get:load.LoadSet.msg)
  return msg_.GetNoArena();
}
inline void LoadSet::set_msg(const ::std::string& value) {
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:load.LoadSet.msg)
}
#if LANG_CXX11
inline void LoadSet::set_msg(::std::string&& value) {
  
  msg_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:load.LoadSet.msg)
}
#endif
inline void LoadSet::set_msg(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:load.LoadSet.msg)
}
inline void LoadSet::set_msg(const char* value, size_t size) {
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:load.LoadSet.msg)
}
inline ::std::string* LoadSet::mutable_msg() {
  
  // @@protoc_insertion_point(field_mutable:load.LoadSet.msg)
  return msg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LoadSet::release_msg() {
  // @@protoc_insertion_point(field_release:load.LoadSet.msg)
  
  return msg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LoadSet::set_allocated_msg(::std::string* msg) {
  if (msg != NULL) {
    
  } else {
    
  }
  msg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), msg);
  // @@protoc_insertion_point(field_set_allocated:load.LoadSet.msg)
}

// -------------------------------------------------------------------

// SchoolConf

// .load.SchoolAtr attr = 1;
inline bool SchoolConf::has_attr() const {
  return this != internal_default_instance() && attr_ != NULL;
}
inline void SchoolConf::clear_attr() {
  if (GetArenaNoVirtual() == NULL && attr_ != NULL) delete attr_;
  attr_ = NULL;
}
inline const ::load::SchoolAtr& SchoolConf::attr() const {
  // @@protoc_insertion_point(field_get:load.SchoolConf.attr)
  return attr_ != NULL ? *attr_
                         : *::load::SchoolAtr::internal_default_instance();
}
inline ::load::SchoolAtr* SchoolConf::mutable_attr() {
  
  if (attr_ == NULL) {
    attr_ = new ::load::SchoolAtr;
  }
  // @@protoc_insertion_point(field_mutable:load.SchoolConf.attr)
  return attr_;
}
inline ::load::SchoolAtr* SchoolConf::release_attr() {
  // @@protoc_insertion_point(field_release:load.SchoolConf.attr)
  
  ::load::SchoolAtr* temp = attr_;
  attr_ = NULL;
  return temp;
}
inline void SchoolConf::set_allocated_attr(::load::SchoolAtr* attr) {
  delete attr_;
  attr_ = attr;
  if (attr) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:load.SchoolConf.attr)
}

// repeated .load.SchoolSudent student = 2;
inline int SchoolConf::student_size() const {
  return student_.size();
}
inline void SchoolConf::clear_student() {
  student_.Clear();
}
inline const ::load::SchoolSudent& SchoolConf::student(int index) const {
  // @@protoc_insertion_point(field_get:load.SchoolConf.student)
  return student_.Get(index);
}
inline ::load::SchoolSudent* SchoolConf::mutable_student(int index) {
  // @@protoc_insertion_point(field_mutable:load.SchoolConf.student)
  return student_.Mutable(index);
}
inline ::load::SchoolSudent* SchoolConf::add_student() {
  // @@protoc_insertion_point(field_add:load.SchoolConf.student)
  return student_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::load::SchoolSudent >*
SchoolConf::mutable_student() {
  // @@protoc_insertion_point(field_mutable_list:load.SchoolConf.student)
  return &student_;
}
inline const ::google::protobuf::RepeatedPtrField< ::load::SchoolSudent >&
SchoolConf::student() const {
  // @@protoc_insertion_point(field_list:load.SchoolConf.student)
  return student_;
}

// -------------------------------------------------------------------

// SchoolAtr

// string name = 1;
inline void SchoolAtr::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& SchoolAtr::name() const {
  // @@protoc_insertion_point(field_get:load.SchoolAtr.name)
  return name_.GetNoArena();
}
inline void SchoolAtr::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:load.SchoolAtr.name)
}
#if LANG_CXX11
inline void SchoolAtr::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:load.SchoolAtr.name)
}
#endif
inline void SchoolAtr::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:load.SchoolAtr.name)
}
inline void SchoolAtr::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:load.SchoolAtr.name)
}
inline ::std::string* SchoolAtr::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:load.SchoolAtr.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SchoolAtr::release_name() {
  // @@protoc_insertion_point(field_release:load.SchoolAtr.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SchoolAtr::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:load.SchoolAtr.name)
}

// int32 student_num = 2;
inline void SchoolAtr::clear_student_num() {
  student_num_ = 0;
}
inline ::google::protobuf::int32 SchoolAtr::student_num() const {
  // @@protoc_insertion_point(field_get:load.SchoolAtr.student_num)
  return student_num_;
}
inline void SchoolAtr::set_student_num(::google::protobuf::int32 value) {
  
  student_num_ = value;
  // @@protoc_insertion_point(field_set:load.SchoolAtr.student_num)
}

// float grade = 3;
inline void SchoolAtr::clear_grade() {
  grade_ = 0;
}
inline float SchoolAtr::grade() const {
  // @@protoc_insertion_point(field_get:load.SchoolAtr.grade)
  return grade_;
}
inline void SchoolAtr::set_grade(float value) {
  
  grade_ = value;
  // @@protoc_insertion_point(field_set:load.SchoolAtr.grade)
}

// -------------------------------------------------------------------

// SchoolSudent

// int32 id = 1;
inline void SchoolSudent::clear_id() {
  id_ = 0;
}
inline ::google::protobuf::int32 SchoolSudent::id() const {
  // @@protoc_insertion_point(field_get:load.SchoolSudent.id)
  return id_;
}
inline void SchoolSudent::set_id(::google::protobuf::int32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:load.SchoolSudent.id)
}

// string name = 2;
inline void SchoolSudent::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& SchoolSudent::name() const {
  // @@protoc_insertion_point(field_get:load.SchoolSudent.name)
  return name_.GetNoArena();
}
inline void SchoolSudent::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:load.SchoolSudent.name)
}
#if LANG_CXX11
inline void SchoolSudent::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:load.SchoolSudent.name)
}
#endif
inline void SchoolSudent::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:load.SchoolSudent.name)
}
inline void SchoolSudent::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:load.SchoolSudent.name)
}
inline ::std::string* SchoolSudent::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:load.SchoolSudent.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SchoolSudent::release_name() {
  // @@protoc_insertion_point(field_release:load.SchoolSudent.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SchoolSudent::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:load.SchoolSudent.name)
}

// repeated int32 scores = 3;
inline int SchoolSudent::scores_size() const {
  return scores_.size();
}
inline void SchoolSudent::clear_scores() {
  scores_.Clear();
}
inline ::google::protobuf::int32 SchoolSudent::scores(int index) const {
  // @@protoc_insertion_point(field_get:load.SchoolSudent.scores)
  return scores_.Get(index);
}
inline void SchoolSudent::set_scores(int index, ::google::protobuf::int32 value) {
  scores_.Set(index, value);
  // @@protoc_insertion_point(field_set:load.SchoolSudent.scores)
}
inline void SchoolSudent::add_scores(::google::protobuf::int32 value) {
  scores_.Add(value);
  // @@protoc_insertion_point(field_add:load.SchoolSudent.scores)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
SchoolSudent::scores() const {
  // @@protoc_insertion_point(field_list:load.SchoolSudent.scores)
  return scores_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
SchoolSudent::mutable_scores() {
  // @@protoc_insertion_point(field_mutable_list:load.SchoolSudent.scores)
  return &scores_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace load

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::load::XmlInfo> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::load::XmlInfo>() {
  return ::load::XmlInfo_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_loadConf_2eproto__INCLUDED
