// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: loadConf.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "loadConf.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace load {
class LoadSetDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<LoadSet> {
} _LoadSet_default_instance_;
class SchoolConfDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<SchoolConf> {
} _SchoolConf_default_instance_;
class SchoolAtrDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<SchoolAtr> {
} _SchoolAtr_default_instance_;
class SchoolSudentDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<SchoolSudent> {
} _SchoolSudent_default_instance_;

namespace protobuf_loadConf_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[4];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoadSet, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoadSet, file_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoadSet, msg_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SchoolConf, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SchoolConf, attr_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SchoolConf, student_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SchoolAtr, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SchoolAtr, name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SchoolAtr, student_num_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SchoolAtr, grade_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SchoolSudent, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SchoolSudent, id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SchoolSudent, name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SchoolSudent, scores_),
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, -1, sizeof(LoadSet)},
  { 7, -1, sizeof(SchoolConf)},
  { 14, -1, sizeof(SchoolAtr)},
  { 22, -1, sizeof(SchoolSudent)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_LoadSet_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_SchoolConf_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_SchoolAtr_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_SchoolSudent_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "loadConf.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 4);
}

}  // namespace

void TableStruct::Shutdown() {
  _LoadSet_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
  _SchoolConf_default_instance_.Shutdown();
  delete file_level_metadata[1].reflection;
  _SchoolAtr_default_instance_.Shutdown();
  delete file_level_metadata[2].reflection;
  _SchoolSudent_default_instance_.Shutdown();
  delete file_level_metadata[3].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  ::google::protobuf::protobuf_google_2fprotobuf_2fdescriptor_2eproto::InitDefaults();
  _LoadSet_default_instance_.DefaultConstruct();
  _SchoolConf_default_instance_.DefaultConstruct();
  _SchoolAtr_default_instance_.DefaultConstruct();
  _SchoolSudent_default_instance_.DefaultConstruct();
  ::google::protobuf::internal::ExtensionSet::RegisterMessageExtension(
    ::google::protobuf::EnumValueOptions::internal_default_instance(),
    1000, 11, false, false,
    ::load::LoadSet::internal_default_instance());
  _SchoolConf_default_instance_.get_mutable()->attr_ = const_cast< ::load::SchoolAtr*>(
      ::load::SchoolAtr::internal_default_instance());
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\016loadConf.proto\022\004load\032 google/protobuf/"
      "descriptor.proto\"$\n\007LoadSet\022\014\n\004file\030\001 \001("
      "\t\022\013\n\003msg\030\002 \001(\t\"P\n\nSchoolConf\022\035\n\004attr\030\001 \001"
      "(\0132\017.load.SchoolAtr\022#\n\007student\030\002 \003(\0132\022.l"
      "oad.SchoolSudent\"=\n\tSchoolAtr\022\014\n\004name\030\001 "
      "\001(\t\022\023\n\013student_num\030\002 \001(\005\022\r\n\005grade\030\003 \001(\002\""
      "8\n\014SchoolSudent\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001("
      "\t\022\016\n\006scores\030\003 \003(\005*D\n\007XmlInfo\022\014\n\010Xml_none"
      "\020\000\022+\n\nXml_school\020\001\032\033\302>\030\n\nschool.xml\022\nSch"
      "oolConf:B\n\007loadset\022!.google.protobuf.Enu"
      "mValueOptions\030\350\007 \001(\0132\r.load.LoadSetb\006pro"
      "to3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 443);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "loadConf.proto", &protobuf_RegisterTypes);
  ::google::protobuf::protobuf_google_2fprotobuf_2fdescriptor_2eproto::AddDescriptors();
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_loadConf_2eproto

const ::google::protobuf::EnumDescriptor* XmlInfo_descriptor() {
  protobuf_loadConf_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_loadConf_2eproto::file_level_enum_descriptors[0];
}
bool XmlInfo_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int LoadSet::kFileFieldNumber;
const int LoadSet::kMsgFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

LoadSet::LoadSet()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_loadConf_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:load.LoadSet)
}
LoadSet::LoadSet(const LoadSet& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  file_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.file().size() > 0) {
    file_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.file_);
  }
  msg_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.msg().size() > 0) {
    msg_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.msg_);
  }
  // @@protoc_insertion_point(copy_constructor:load.LoadSet)
}

void LoadSet::SharedCtor() {
  file_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  msg_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _cached_size_ = 0;
}

LoadSet::~LoadSet() {
  // @@protoc_insertion_point(destructor:load.LoadSet)
  SharedDtor();
}

void LoadSet::SharedDtor() {
  file_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  msg_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void LoadSet::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* LoadSet::descriptor() {
  protobuf_loadConf_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_loadConf_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const LoadSet& LoadSet::default_instance() {
  protobuf_loadConf_2eproto::InitDefaults();
  return *internal_default_instance();
}

LoadSet* LoadSet::New(::google::protobuf::Arena* arena) const {
  LoadSet* n = new LoadSet;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void LoadSet::Clear() {
// @@protoc_insertion_point(message_clear_start:load.LoadSet)
  file_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool LoadSet::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:load.LoadSet)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string file = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_file()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->file().data(), this->file().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "load.LoadSet.file"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string msg = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_msg()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->msg().data(), this->msg().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "load.LoadSet.msg"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:load.LoadSet)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:load.LoadSet)
  return false;
#undef DO_
}

void LoadSet::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:load.LoadSet)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string file = 1;
  if (this->file().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->file().data(), this->file().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "load.LoadSet.file");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->file(), output);
  }

  // string msg = 2;
  if (this->msg().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->msg().data(), this->msg().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "load.LoadSet.msg");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->msg(), output);
  }

  // @@protoc_insertion_point(serialize_end:load.LoadSet)
}

::google::protobuf::uint8* LoadSet::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:load.LoadSet)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string file = 1;
  if (this->file().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->file().data(), this->file().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "load.LoadSet.file");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->file(), target);
  }

  // string msg = 2;
  if (this->msg().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->msg().data(), this->msg().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "load.LoadSet.msg");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->msg(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:load.LoadSet)
  return target;
}

size_t LoadSet::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:load.LoadSet)
  size_t total_size = 0;

  // string file = 1;
  if (this->file().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->file());
  }

  // string msg = 2;
  if (this->msg().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->msg());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void LoadSet::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:load.LoadSet)
  GOOGLE_DCHECK_NE(&from, this);
  const LoadSet* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const LoadSet>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:load.LoadSet)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:load.LoadSet)
    MergeFrom(*source);
  }
}

void LoadSet::MergeFrom(const LoadSet& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:load.LoadSet)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.file().size() > 0) {

    file_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.file_);
  }
  if (from.msg().size() > 0) {

    msg_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.msg_);
  }
}

void LoadSet::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:load.LoadSet)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void LoadSet::CopyFrom(const LoadSet& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:load.LoadSet)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LoadSet::IsInitialized() const {
  return true;
}

void LoadSet::Swap(LoadSet* other) {
  if (other == this) return;
  InternalSwap(other);
}
void LoadSet::InternalSwap(LoadSet* other) {
  file_.Swap(&other->file_);
  msg_.Swap(&other->msg_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata LoadSet::GetMetadata() const {
  protobuf_loadConf_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_loadConf_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// LoadSet

// string file = 1;
void LoadSet::clear_file() {
  file_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& LoadSet::file() const {
  // @@protoc_insertion_point(field_get:load.LoadSet.file)
  return file_.GetNoArena();
}
void LoadSet::set_file(const ::std::string& value) {
  
  file_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:load.LoadSet.file)
}
#if LANG_CXX11
void LoadSet::set_file(::std::string&& value) {
  
  file_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:load.LoadSet.file)
}
#endif
void LoadSet::set_file(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  file_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:load.LoadSet.file)
}
void LoadSet::set_file(const char* value, size_t size) {
  
  file_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:load.LoadSet.file)
}
::std::string* LoadSet::mutable_file() {
  
  // @@protoc_insertion_point(field_mutable:load.LoadSet.file)
  return file_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* LoadSet::release_file() {
  // @@protoc_insertion_point(field_release:load.LoadSet.file)
  
  return file_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void LoadSet::set_allocated_file(::std::string* file) {
  if (file != NULL) {
    
  } else {
    
  }
  file_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), file);
  // @@protoc_insertion_point(field_set_allocated:load.LoadSet.file)
}

// string msg = 2;
void LoadSet::clear_msg() {
  msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& LoadSet::msg() const {
  // @@protoc_insertion_point(field_get:load.LoadSet.msg)
  return msg_.GetNoArena();
}
void LoadSet::set_msg(const ::std::string& value) {
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:load.LoadSet.msg)
}
#if LANG_CXX11
void LoadSet::set_msg(::std::string&& value) {
  
  msg_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:load.LoadSet.msg)
}
#endif
void LoadSet::set_msg(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:load.LoadSet.msg)
}
void LoadSet::set_msg(const char* value, size_t size) {
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:load.LoadSet.msg)
}
::std::string* LoadSet::mutable_msg() {
  
  // @@protoc_insertion_point(field_mutable:load.LoadSet.msg)
  return msg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* LoadSet::release_msg() {
  // @@protoc_insertion_point(field_release:load.LoadSet.msg)
  
  return msg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void LoadSet::set_allocated_msg(::std::string* msg) {
  if (msg != NULL) {
    
  } else {
    
  }
  msg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), msg);
  // @@protoc_insertion_point(field_set_allocated:load.LoadSet.msg)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SchoolConf::kAttrFieldNumber;
const int SchoolConf::kStudentFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SchoolConf::SchoolConf()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_loadConf_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:load.SchoolConf)
}
SchoolConf::SchoolConf(const SchoolConf& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      student_(from.student_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_attr()) {
    attr_ = new ::load::SchoolAtr(*from.attr_);
  } else {
    attr_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:load.SchoolConf)
}

void SchoolConf::SharedCtor() {
  attr_ = NULL;
  _cached_size_ = 0;
}

SchoolConf::~SchoolConf() {
  // @@protoc_insertion_point(destructor:load.SchoolConf)
  SharedDtor();
}

void SchoolConf::SharedDtor() {
  if (this != internal_default_instance()) {
    delete attr_;
  }
}

void SchoolConf::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SchoolConf::descriptor() {
  protobuf_loadConf_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_loadConf_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SchoolConf& SchoolConf::default_instance() {
  protobuf_loadConf_2eproto::InitDefaults();
  return *internal_default_instance();
}

SchoolConf* SchoolConf::New(::google::protobuf::Arena* arena) const {
  SchoolConf* n = new SchoolConf;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SchoolConf::Clear() {
// @@protoc_insertion_point(message_clear_start:load.SchoolConf)
  student_.Clear();
  if (GetArenaNoVirtual() == NULL && attr_ != NULL) {
    delete attr_;
  }
  attr_ = NULL;
}

bool SchoolConf::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:load.SchoolConf)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .load.SchoolAtr attr = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_attr()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .load.SchoolSudent student = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_student()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:load.SchoolConf)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:load.SchoolConf)
  return false;
#undef DO_
}

void SchoolConf::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:load.SchoolConf)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .load.SchoolAtr attr = 1;
  if (this->has_attr()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->attr_, output);
  }

  // repeated .load.SchoolSudent student = 2;
  for (unsigned int i = 0, n = this->student_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->student(i), output);
  }

  // @@protoc_insertion_point(serialize_end:load.SchoolConf)
}

::google::protobuf::uint8* SchoolConf::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:load.SchoolConf)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .load.SchoolAtr attr = 1;
  if (this->has_attr()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, *this->attr_, deterministic, target);
  }

  // repeated .load.SchoolSudent student = 2;
  for (unsigned int i = 0, n = this->student_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, this->student(i), deterministic, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:load.SchoolConf)
  return target;
}

size_t SchoolConf::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:load.SchoolConf)
  size_t total_size = 0;

  // repeated .load.SchoolSudent student = 2;
  {
    unsigned int count = this->student_size();
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->student(i));
    }
  }

  // .load.SchoolAtr attr = 1;
  if (this->has_attr()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->attr_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SchoolConf::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:load.SchoolConf)
  GOOGLE_DCHECK_NE(&from, this);
  const SchoolConf* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SchoolConf>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:load.SchoolConf)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:load.SchoolConf)
    MergeFrom(*source);
  }
}

void SchoolConf::MergeFrom(const SchoolConf& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:load.SchoolConf)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  student_.MergeFrom(from.student_);
  if (from.has_attr()) {
    mutable_attr()->::load::SchoolAtr::MergeFrom(from.attr());
  }
}

void SchoolConf::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:load.SchoolConf)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SchoolConf::CopyFrom(const SchoolConf& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:load.SchoolConf)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SchoolConf::IsInitialized() const {
  return true;
}

void SchoolConf::Swap(SchoolConf* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SchoolConf::InternalSwap(SchoolConf* other) {
  student_.InternalSwap(&other->student_);
  std::swap(attr_, other->attr_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata SchoolConf::GetMetadata() const {
  protobuf_loadConf_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_loadConf_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// SchoolConf

// .load.SchoolAtr attr = 1;
bool SchoolConf::has_attr() const {
  return this != internal_default_instance() && attr_ != NULL;
}
void SchoolConf::clear_attr() {
  if (GetArenaNoVirtual() == NULL && attr_ != NULL) delete attr_;
  attr_ = NULL;
}
const ::load::SchoolAtr& SchoolConf::attr() const {
  // @@protoc_insertion_point(field_get:load.SchoolConf.attr)
  return attr_ != NULL ? *attr_
                         : *::load::SchoolAtr::internal_default_instance();
}
::load::SchoolAtr* SchoolConf::mutable_attr() {
  
  if (attr_ == NULL) {
    attr_ = new ::load::SchoolAtr;
  }
  // @@protoc_insertion_point(field_mutable:load.SchoolConf.attr)
  return attr_;
}
::load::SchoolAtr* SchoolConf::release_attr() {
  // @@protoc_insertion_point(field_release:load.SchoolConf.attr)
  
  ::load::SchoolAtr* temp = attr_;
  attr_ = NULL;
  return temp;
}
void SchoolConf::set_allocated_attr(::load::SchoolAtr* attr) {
  delete attr_;
  attr_ = attr;
  if (attr) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:load.SchoolConf.attr)
}

// repeated .load.SchoolSudent student = 2;
int SchoolConf::student_size() const {
  return student_.size();
}
void SchoolConf::clear_student() {
  student_.Clear();
}
const ::load::SchoolSudent& SchoolConf::student(int index) const {
  // @@protoc_insertion_point(field_get:load.SchoolConf.student)
  return student_.Get(index);
}
::load::SchoolSudent* SchoolConf::mutable_student(int index) {
  // @@protoc_insertion_point(field_mutable:load.SchoolConf.student)
  return student_.Mutable(index);
}
::load::SchoolSudent* SchoolConf::add_student() {
  // @@protoc_insertion_point(field_add:load.SchoolConf.student)
  return student_.Add();
}
::google::protobuf::RepeatedPtrField< ::load::SchoolSudent >*
SchoolConf::mutable_student() {
  // @@protoc_insertion_point(field_mutable_list:load.SchoolConf.student)
  return &student_;
}
const ::google::protobuf::RepeatedPtrField< ::load::SchoolSudent >&
SchoolConf::student() const {
  // @@protoc_insertion_point(field_list:load.SchoolConf.student)
  return student_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SchoolAtr::kNameFieldNumber;
const int SchoolAtr::kStudentNumFieldNumber;
const int SchoolAtr::kGradeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SchoolAtr::SchoolAtr()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_loadConf_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:load.SchoolAtr)
}
SchoolAtr::SchoolAtr(const SchoolAtr& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.name().size() > 0) {
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  ::memcpy(&student_num_, &from.student_num_,
    reinterpret_cast<char*>(&grade_) -
    reinterpret_cast<char*>(&student_num_) + sizeof(grade_));
  // @@protoc_insertion_point(copy_constructor:load.SchoolAtr)
}

void SchoolAtr::SharedCtor() {
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&student_num_, 0, reinterpret_cast<char*>(&grade_) -
    reinterpret_cast<char*>(&student_num_) + sizeof(grade_));
  _cached_size_ = 0;
}

SchoolAtr::~SchoolAtr() {
  // @@protoc_insertion_point(destructor:load.SchoolAtr)
  SharedDtor();
}

void SchoolAtr::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void SchoolAtr::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SchoolAtr::descriptor() {
  protobuf_loadConf_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_loadConf_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SchoolAtr& SchoolAtr::default_instance() {
  protobuf_loadConf_2eproto::InitDefaults();
  return *internal_default_instance();
}

SchoolAtr* SchoolAtr::New(::google::protobuf::Arena* arena) const {
  SchoolAtr* n = new SchoolAtr;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SchoolAtr::Clear() {
// @@protoc_insertion_point(message_clear_start:load.SchoolAtr)
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&student_num_, 0, reinterpret_cast<char*>(&grade_) -
    reinterpret_cast<char*>(&student_num_) + sizeof(grade_));
}

bool SchoolAtr::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:load.SchoolAtr)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "load.SchoolAtr.name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 student_num = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &student_num_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float grade = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(29u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &grade_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:load.SchoolAtr)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:load.SchoolAtr)
  return false;
#undef DO_
}

void SchoolAtr::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:load.SchoolAtr)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "load.SchoolAtr.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // int32 student_num = 2;
  if (this->student_num() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->student_num(), output);
  }

  // float grade = 3;
  if (this->grade() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->grade(), output);
  }

  // @@protoc_insertion_point(serialize_end:load.SchoolAtr)
}

::google::protobuf::uint8* SchoolAtr::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:load.SchoolAtr)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "load.SchoolAtr.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // int32 student_num = 2;
  if (this->student_num() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->student_num(), target);
  }

  // float grade = 3;
  if (this->grade() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->grade(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:load.SchoolAtr)
  return target;
}

size_t SchoolAtr::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:load.SchoolAtr)
  size_t total_size = 0;

  // string name = 1;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  // int32 student_num = 2;
  if (this->student_num() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->student_num());
  }

  // float grade = 3;
  if (this->grade() != 0) {
    total_size += 1 + 4;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SchoolAtr::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:load.SchoolAtr)
  GOOGLE_DCHECK_NE(&from, this);
  const SchoolAtr* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SchoolAtr>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:load.SchoolAtr)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:load.SchoolAtr)
    MergeFrom(*source);
  }
}

void SchoolAtr::MergeFrom(const SchoolAtr& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:load.SchoolAtr)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.student_num() != 0) {
    set_student_num(from.student_num());
  }
  if (from.grade() != 0) {
    set_grade(from.grade());
  }
}

void SchoolAtr::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:load.SchoolAtr)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SchoolAtr::CopyFrom(const SchoolAtr& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:load.SchoolAtr)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SchoolAtr::IsInitialized() const {
  return true;
}

void SchoolAtr::Swap(SchoolAtr* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SchoolAtr::InternalSwap(SchoolAtr* other) {
  name_.Swap(&other->name_);
  std::swap(student_num_, other->student_num_);
  std::swap(grade_, other->grade_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata SchoolAtr::GetMetadata() const {
  protobuf_loadConf_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_loadConf_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// SchoolAtr

// string name = 1;
void SchoolAtr::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& SchoolAtr::name() const {
  // @@protoc_insertion_point(field_get:load.SchoolAtr.name)
  return name_.GetNoArena();
}
void SchoolAtr::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:load.SchoolAtr.name)
}
#if LANG_CXX11
void SchoolAtr::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:load.SchoolAtr.name)
}
#endif
void SchoolAtr::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:load.SchoolAtr.name)
}
void SchoolAtr::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:load.SchoolAtr.name)
}
::std::string* SchoolAtr::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:load.SchoolAtr.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* SchoolAtr::release_name() {
  // @@protoc_insertion_point(field_release:load.SchoolAtr.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void SchoolAtr::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:load.SchoolAtr.name)
}

// int32 student_num = 2;
void SchoolAtr::clear_student_num() {
  student_num_ = 0;
}
::google::protobuf::int32 SchoolAtr::student_num() const {
  // @@protoc_insertion_point(field_get:load.SchoolAtr.student_num)
  return student_num_;
}
void SchoolAtr::set_student_num(::google::protobuf::int32 value) {
  
  student_num_ = value;
  // @@protoc_insertion_point(field_set:load.SchoolAtr.student_num)
}

// float grade = 3;
void SchoolAtr::clear_grade() {
  grade_ = 0;
}
float SchoolAtr::grade() const {
  // @@protoc_insertion_point(field_get:load.SchoolAtr.grade)
  return grade_;
}
void SchoolAtr::set_grade(float value) {
  
  grade_ = value;
  // @@protoc_insertion_point(field_set:load.SchoolAtr.grade)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SchoolSudent::kIdFieldNumber;
const int SchoolSudent::kNameFieldNumber;
const int SchoolSudent::kScoresFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SchoolSudent::SchoolSudent()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_loadConf_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:load.SchoolSudent)
}
SchoolSudent::SchoolSudent(const SchoolSudent& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      scores_(from.scores_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.name().size() > 0) {
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  id_ = from.id_;
  // @@protoc_insertion_point(copy_constructor:load.SchoolSudent)
}

void SchoolSudent::SharedCtor() {
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  id_ = 0;
  _cached_size_ = 0;
}

SchoolSudent::~SchoolSudent() {
  // @@protoc_insertion_point(destructor:load.SchoolSudent)
  SharedDtor();
}

void SchoolSudent::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void SchoolSudent::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SchoolSudent::descriptor() {
  protobuf_loadConf_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_loadConf_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SchoolSudent& SchoolSudent::default_instance() {
  protobuf_loadConf_2eproto::InitDefaults();
  return *internal_default_instance();
}

SchoolSudent* SchoolSudent::New(::google::protobuf::Arena* arena) const {
  SchoolSudent* n = new SchoolSudent;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SchoolSudent::Clear() {
// @@protoc_insertion_point(message_clear_start:load.SchoolSudent)
  scores_.Clear();
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  id_ = 0;
}

bool SchoolSudent::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:load.SchoolSudent)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string name = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "load.SchoolSudent.name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated int32 scores = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_scores())));
        } else if (static_cast< ::google::protobuf::uint8>(tag) ==
                   static_cast< ::google::protobuf::uint8>(24u)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 26u, input, this->mutable_scores())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:load.SchoolSudent)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:load.SchoolSudent)
  return false;
#undef DO_
}

void SchoolSudent::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:load.SchoolSudent)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 id = 1;
  if (this->id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->id(), output);
  }

  // string name = 2;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "load.SchoolSudent.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->name(), output);
  }

  // repeated int32 scores = 3;
  if (this->scores_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(3, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_scores_cached_byte_size_);
  }
  for (int i = 0, n = this->scores_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32NoTag(
      this->scores(i), output);
  }

  // @@protoc_insertion_point(serialize_end:load.SchoolSudent)
}

::google::protobuf::uint8* SchoolSudent::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:load.SchoolSudent)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 id = 1;
  if (this->id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->id(), target);
  }

  // string name = 2;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "load.SchoolSudent.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->name(), target);
  }

  // repeated int32 scores = 3;
  if (this->scores_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      3,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
      _scores_cached_byte_size_, target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32NoTagToArray(this->scores_, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:load.SchoolSudent)
  return target;
}

size_t SchoolSudent::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:load.SchoolSudent)
  size_t total_size = 0;

  // repeated int32 scores = 3;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      Int32Size(this->scores_);
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(data_size);
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _scores_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // string name = 2;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  // int32 id = 1;
  if (this->id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->id());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SchoolSudent::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:load.SchoolSudent)
  GOOGLE_DCHECK_NE(&from, this);
  const SchoolSudent* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SchoolSudent>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:load.SchoolSudent)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:load.SchoolSudent)
    MergeFrom(*source);
  }
}

void SchoolSudent::MergeFrom(const SchoolSudent& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:load.SchoolSudent)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  scores_.MergeFrom(from.scores_);
  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.id() != 0) {
    set_id(from.id());
  }
}

void SchoolSudent::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:load.SchoolSudent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SchoolSudent::CopyFrom(const SchoolSudent& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:load.SchoolSudent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SchoolSudent::IsInitialized() const {
  return true;
}

void SchoolSudent::Swap(SchoolSudent* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SchoolSudent::InternalSwap(SchoolSudent* other) {
  scores_.InternalSwap(&other->scores_);
  name_.Swap(&other->name_);
  std::swap(id_, other->id_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata SchoolSudent::GetMetadata() const {
  protobuf_loadConf_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_loadConf_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// SchoolSudent

// int32 id = 1;
void SchoolSudent::clear_id() {
  id_ = 0;
}
::google::protobuf::int32 SchoolSudent::id() const {
  // @@protoc_insertion_point(field_get:load.SchoolSudent.id)
  return id_;
}
void SchoolSudent::set_id(::google::protobuf::int32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:load.SchoolSudent.id)
}

// string name = 2;
void SchoolSudent::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& SchoolSudent::name() const {
  // @@protoc_insertion_point(field_get:load.SchoolSudent.name)
  return name_.GetNoArena();
}
void SchoolSudent::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:load.SchoolSudent.name)
}
#if LANG_CXX11
void SchoolSudent::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:load.SchoolSudent.name)
}
#endif
void SchoolSudent::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:load.SchoolSudent.name)
}
void SchoolSudent::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:load.SchoolSudent.name)
}
::std::string* SchoolSudent::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:load.SchoolSudent.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* SchoolSudent::release_name() {
  // @@protoc_insertion_point(field_release:load.SchoolSudent.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void SchoolSudent::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:load.SchoolSudent.name)
}

// repeated int32 scores = 3;
int SchoolSudent::scores_size() const {
  return scores_.size();
}
void SchoolSudent::clear_scores() {
  scores_.Clear();
}
::google::protobuf::int32 SchoolSudent::scores(int index) const {
  // @@protoc_insertion_point(field_get:load.SchoolSudent.scores)
  return scores_.Get(index);
}
void SchoolSudent::set_scores(int index, ::google::protobuf::int32 value) {
  scores_.Set(index, value);
  // @@protoc_insertion_point(field_set:load.SchoolSudent.scores)
}
void SchoolSudent::add_scores(::google::protobuf::int32 value) {
  scores_.Add(value);
  // @@protoc_insertion_point(field_add:load.SchoolSudent.scores)
}
const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
SchoolSudent::scores() const {
  // @@protoc_insertion_point(field_list:load.SchoolSudent.scores)
  return scores_;
}
::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
SchoolSudent::mutable_scores() {
  // @@protoc_insertion_point(field_mutable_list:load.SchoolSudent.scores)
  return &scores_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::EnumValueOptions,
    ::google::protobuf::internal::MessageTypeTraits< ::load::LoadSet >, 11, false >
  loadset(kLoadsetFieldNumber, *::load::LoadSet::internal_default_instance());

// @@protoc_insertion_point(namespace_scope)

}  // namespace load

// @@protoc_insertion_point(global_scope)
